configfile:
  - ny_profiles/ny_builds.yaml
  - ny_profiles/input.yaml

cores: 8
keep-going: True
printshellcmds: True
reason: True
show-failed-logs: True
restart-times: 1
stats: stats.json
set-threads: tree=4